import React from 'react';
import {
  Square,
  Columns,
  Type,
  MousePointer2,
  Image as ImageIcon,
  Minus,
  Space,
  Share2,
  Box,
  Globe,
  Code,
  FileText,
  Tag,
  AlignLeft,
  Layers,
  Film,
  Link,
  Menu,
  List,
  Table,
  ChevronDown,
  Star,
  Eye,
  Palette,
  BookOpen,
  Sliders,
  LayoutTemplate,
} from 'lucide-react';
import { MJComponentType } from './types';

export type ComponentGroup = 'head' | 'layout' | 'content' | 'interactive' | 'navigation' | 'social';

export interface ComponentDef {
  type: MJComponentType;
  label: string;
  icon: React.ReactNode;
  defaultAttrs: Record<string, string>;
  isContainer: boolean;
  group: ComponentGroup;
  /** Default children to seed when dropped (optional) */
  defaultContent?: string;
}

export const MJML_COMPONENTS: ComponentDef[] = [

  // ── HEAD ──────────────────────────────────────────────────────────────────
  {
    type: 'mj-attributes',
    label: 'Attributes',
    icon: <Sliders size={16} />,
    group: 'head',
    isContainer: false,
    defaultAttrs: {},
    defaultContent: '',
  },
  {
    type: 'mj-breakpoint',
    label: 'Breakpoint',
    icon: <Sliders size={16} />,
    group: 'head',
    isContainer: false,
    defaultAttrs: { width: '480px' },
  },
  {
    type: 'mj-font',
    label: 'Font',
    icon: <Type size={16} />,
    group: 'head',
    isContainer: false,
    defaultAttrs: {
      name: 'Inter',
      href: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap',
    },
  },
  {
    type: 'mj-html-attributes',
    label: 'HTML Attributes',
    icon: <Tag size={16} />,
    group: 'head',
    isContainer: false,
    defaultAttrs: {},
  },
  {
    type: 'mj-preview',
    label: 'Preview',
    icon: <Eye size={16} />,
    group: 'head',
    isContainer: false,
    defaultAttrs: {},
    defaultContent: 'Preview text shown in inbox…',
  },
  {
    type: 'mj-style',
    label: 'Style',
    icon: <Palette size={16} />,
    group: 'head',
    isContainer: false,
    defaultAttrs: { inline: 'inline' },
    defaultContent: '.custom { }',
  },
  {
    type: 'mj-title',
    label: 'Title',
    icon: <FileText size={16} />,
    group: 'head',
    isContainer: false,
    defaultAttrs: {},
    defaultContent: 'Email Subject',
  },

  // ── LAYOUT ────────────────────────────────────────────────────────────────
  {
    type: 'mj-wrapper',
    label: 'Wrapper',
    icon: <Box size={16} />,
    group: 'layout',
    isContainer: true,
    defaultAttrs: {
      'background-color': '#f4f4f4',
      'background-url': '',
      'background-size': 'cover',
      padding: '20px 0',
      'mj-class': '',
    },
  },
  {
    type: 'mj-section',
    label: 'Section',
    icon: <Square size={16} />,
    group: 'layout',
    isContainer: true,
    defaultAttrs: {
      'background-color': '#ffffff',
      'background-url': '',
      'background-size': 'cover',
      padding: '20px 0',
      'mj-class': '',
    },
  },
  {
    type: 'mj-column',
    label: 'Column',
    icon: <Columns size={16} />,
    group: 'layout',
    isContainer: true,
    defaultAttrs: { width: '100%', 'mj-class': '' },
  },
  {
    type: 'mj-group',
    label: 'Group',
    icon: <LayoutTemplate size={16} />,
    group: 'layout',
    isContainer: true,
    defaultAttrs: { width: '100%', direction: 'ltr', 'mj-class': '' },
  },
  {
    type: 'mj-hero',
    label: 'Hero',
    icon: <Star size={16} />,
    group: 'layout',
    isContainer: true,
    defaultAttrs: {
      mode: 'fixed-height',
      height: '469px',
      'background-color': '#ffffff',
      'background-url': '',
      'background-position': 'center center',
      padding: '100px 0px',
      'mj-class': '',
    },
  },

  // ── CONTENT ───────────────────────────────────────────────────────────────
  {
    type: 'mj-text',
    label: 'Text',
    icon: <Type size={16} />,
    group: 'content',
    isContainer: false,
    defaultAttrs: {
      color: '#262628',
      'font-family': 'Inter, sans-serif',
      'font-size': '14px',
      'line-height': '1.6',
      'container-background-color': '',
      padding: '10px 25px',
      'mj-class': '',
    },
    defaultContent: 'Edit this text…',
  },
  {
    type: 'mj-button',
    label: 'Button',
    icon: <MousePointer2 size={16} />,
    group: 'content',
    isContainer: false,
    defaultAttrs: {
      'background-color': '#006dd8',
      color: '#ffffff',
      'border-radius': '4px',
      padding: '10px 25px',
      'font-family': 'Inter, sans-serif',
      'font-size': '13px',
      href: '#',
      'mj-class': '',
    },
    defaultContent: 'Click here',
  },
  {
    type: 'mj-image',
    label: 'Image',
    icon: <ImageIcon size={16} />,
    group: 'content',
    isContainer: false,
    defaultAttrs: {
      src: 'https://picsum.photos/600/300',
      width: '600px',
      padding: '0',
      align: 'center',
      alt: '',
      'mj-class': '',
    },
  },
  {
    type: 'mj-divider',
    label: 'Divider',
    icon: <Minus size={16} />,
    group: 'content',
    isContainer: false,
    defaultAttrs: {
      'border-color': '#e0e0e0',
      'border-style': 'solid',
      'border-width': '1px',
      padding: '10px 25px',
      'mj-class': '',
    },
  },
  {
    type: 'mj-spacer',
    label: 'Spacer',
    icon: <Space size={16} />,
    group: 'content',
    isContainer: false,
    defaultAttrs: { height: '20px', 'mj-class': '' },
  },
  {
    type: 'mj-table',
    label: 'Table',
    icon: <Table size={16} />,
    group: 'content',
    isContainer: false,
    defaultAttrs: {
      color: '#262628',
      'font-family': 'Inter, sans-serif',
      'font-size': '13px',
      padding: '10px 25px',
      'mj-class': '',
    },
    defaultContent: '<tr><th>Header</th><th>Header</th></tr><tr><td>Cell</td><td>Cell</td></tr>',
  },
  {
    type: 'mj-raw',
    label: 'Raw HTML',
    icon: <Code size={16} />,
    group: 'content',
    isContainer: false,
    defaultAttrs: {},
    defaultContent: '<!-- raw HTML here -->',
  },

  // ── INTERACTIVE ───────────────────────────────────────────────────────────
  {
    type: 'mj-accordion',
    label: 'Accordion',
    icon: <ChevronDown size={16} />,
    group: 'interactive',
    isContainer: true,
    defaultAttrs: {
      border: 'none',
      padding: '1px',
      'font-family': 'Inter, sans-serif',
      'mj-class': '',
    },
  },
  {
    type: 'mj-accordion-element',
    label: 'Accordion Item',
    icon: <AlignLeft size={16} />,
    group: 'interactive',
    isContainer: true,
    defaultAttrs: {
      'icon-wrapped-url': 'https://i.imgur.com/w4uTygT.png',
      'icon-unwrapped-url': 'https://i.imgur.com/bIXv1bk.png',
      'icon-height': '24px',
      'icon-width': '24px',
      'mj-class': '',
    },
  },
  {
    type: 'mj-accordion-title',
    label: 'Accordion Title',
    icon: <BookOpen size={16} />,
    group: 'interactive',
    isContainer: false,
    defaultAttrs: {
      color: '#031017',
      'background-color': '#ffffff',
      'font-family': 'Inter, sans-serif',
      'font-size': '16px',
      padding: '15px',
      'mj-class': '',
    },
    defaultContent: 'Accordion Title',
  },
  {
    type: 'mj-accordion-text',
    label: 'Accordion Text',
    icon: <AlignLeft size={16} />,
    group: 'interactive',
    isContainer: false,
    defaultAttrs: {
      color: '#505050',
      'background-color': '#fafafa',
      'font-family': 'Inter, sans-serif',
      'font-size': '14px',
      padding: '15px',
      'mj-class': '',
    },
    defaultContent: 'Accordion body content goes here.',
  },
  {
    type: 'mj-carousel',
    label: 'Carousel',
    icon: <Film size={16} />,
    group: 'interactive',
    isContainer: true,
    defaultAttrs: {
      align: 'center',
      'border-radius': '6px',
      'thumbnail-border': '2px solid transparent',
      'thumbnail-border-radius': '6px',
      'mj-class': '',
    },
  },
  {
    type: 'mj-carousel-image',
    label: 'Carousel Image',
    icon: <ImageIcon size={16} />,
    group: 'interactive',
    isContainer: false,
    defaultAttrs: {
      src: 'https://picsum.photos/600/300',
      alt: '',
      href: '#',
      target: '_blank',
      'mj-class': '',
    },
  },

  // ── NAVIGATION ────────────────────────────────────────────────────────────
  {
    type: 'mj-navbar',
    label: 'Navbar',
    icon: <Menu size={16} />,
    group: 'navigation',
    isContainer: true,
    defaultAttrs: {
      align: 'center',
      'base-url': 'https://example.com',
      hamburger: 'hamburger',
      'ico-open': '&#9776;',
      'ico-close': '&#8855;',
      'mj-class': '',
    },
  },
  {
    type: 'mj-navbar-link',
    label: 'Navbar Link',
    icon: <Link size={16} />,
    group: 'navigation',
    isContainer: false,
    defaultAttrs: {
      href: '#',
      target: '_blank',
      color: '#262628',
      'font-family': 'Inter, sans-serif',
      'font-size': '13px',
      padding: '15px 10px',
      'mj-class': '',
    },
    defaultContent: 'Nav Link',
  },

  // ── SOCIAL ────────────────────────────────────────────────────────────────
  {
    type: 'mj-social',
    label: 'Social',
    icon: <Share2 size={16} />,
    group: 'social',
    isContainer: true,
    defaultAttrs: {
      align: 'center',
      'font-family': 'Inter, sans-serif',
      'font-size': '13px',
      'icon-size': '20px',
      mode: 'horizontal',
      padding: '10px 25px',
      'mj-class': '',
    },
  },
  {
    type: 'mj-social-element',
    label: 'Social Link',
    icon: <Globe size={16} />,
    group: 'social',
    isContainer: false,
    defaultAttrs: {
      name: 'facebook',
      href: 'https://www.facebook.com/',
      'background-color': '#3b5998',
      color: '#ffffff',
      'font-family': 'Inter, sans-serif',
      'font-size': '13px',
      'mj-class': '',
    },
    defaultContent: 'Facebook',
  },
];

// Groups for the sidebar
export const COMPONENT_GROUPS: { key: ComponentGroup; label: string }[] = [
  { key: 'head', label: 'Head' },
  { key: 'layout', label: 'Layout' },
  { key: 'content', label: 'Content' },
  { key: 'interactive', label: 'Interactive' },
  { key: 'navigation', label: 'Navigation' },
  { key: 'social', label: 'Social' },
];
